export const investmentTopics = [
  { id:"stocks", emoji:"📈", title:"Stocks & Equities", tagline:"Own a piece of real companies", riskLevel:"Medium", readTime:"8 min", description:"Stocks represent ownership in a company. When the company grows, your investment grows too. Learn how to pick quality stocks and when to buy.", content:`**What is a stock?**\nA stock is a share of ownership in a company. When you buy Apple stock, you own a tiny piece of Apple Inc.\n\n**How do you make money?**\n1. Price appreciation — the stock goes up in value\n2. Dividends — some companies pay you cash quarterly\n\n**Key metrics to understand:**\n- P/E Ratio: Price relative to earnings (lower = potentially cheaper)\n- Market Cap: Total company value\n- Dividend Yield: Annual cash return %\n\n**Where to buy stocks (US):**\nFidelity, Schwab, or Robinhood. Start with index funds if unsure.\n\n**Golden rule:** Don't invest money you'll need in less than 5 years.` },
  { id:"etfs", emoji:"🧺", title:"ETFs & Index Funds", tagline:"Diversification made simple", riskLevel:"Low-Medium", readTime:"7 min", description:"ETFs let you buy hundreds of stocks at once for a low cost. They are the #1 recommended starting point for beginners.", content:`**What is an ETF?**\nAn Exchange-Traded Fund holds a basket of assets. SPY holds the 500 largest US companies in one fund.\n\n**Why ETFs are great for beginners:**\n- Instant diversification\n- Very low fees (0.03% - 0.20% per year)\n- No stock-picking required\n- Proven long-term returns\n\n**Top beginner ETFs:**\n- VTI — Total US stock market\n- VXUS — International stocks\n- BND — US bonds\n- VOO — S&P 500 index\n\n**Historical average:** The S&P 500 has returned ~10% per year on average since 1957.\n\n**How to start:** Open a brokerage account at Fidelity or Schwab. Buy $100 of VOO. That's it.` },
  { id:"bonds", emoji:"🏦", title:"Bonds & Fixed Income", tagline:"Steady, predictable returns", riskLevel:"Low", readTime:"6 min", description:"Bonds are loans you give to governments or companies. They pay you interest on a schedule. Perfect for conservative savers.", content:`**What is a bond?**\nWhen you buy a bond, you lend money to a government or corporation. They promise to pay you interest and return your principal at a set date.\n\n**Types of bonds:**\n1. US Treasury Bonds — backed by the US government (safest)\n2. Corporate Bonds — higher yield, slightly more risk\n3. Municipal Bonds — tax advantages for US investors\n4. I-Bonds — inflation-protected savings bonds\n\n**Current yields (approx):**\n- 1-Year Treasury: ~5%\n- 10-Year Treasury: ~4.5%\n- I-Bond: inflation + fixed rate\n\n**Where to buy:**\n- TreasuryDirect.gov for US Treasuries (no fees)\n- Any brokerage for bond ETFs (BND, AGG)\n\n**Best for:** Money you need in 1-5 years. Lower risk than stocks.` },
  { id:"realestate", emoji:"🏠", title:"Real Estate Investing", tagline:"Build wealth through property", riskLevel:"Medium-High", readTime:"10 min", description:"Real estate can generate rental income and appreciation. You don't need to be a landlord — REITs let you invest with just $1.", content:`**Ways to invest in real estate:**\n1. Buy rental property (requires large capital)\n2. REITs — Real Estate Investment Trusts (like stock market for properties)\n3. Real estate ETFs (VNQ, SCHH)\n4. Crowdfunding platforms (Fundrise, RealtyMogul)\n\n**REITs explained:**\nREITs must pay 90% of taxable income as dividends. They trade on stock exchanges. You can buy with $1 on any brokerage.\n\n**Top REIT ETFs:**\n- VNQ — Vanguard Real Estate ETF\n- SCHH — Schwab US REIT ETF\n\n**Average returns:** REITs have historically returned 10-12% annually including dividends.\n\n**For car/home buyers:** Real estate appreciation in your target area affects how much you need to save.` },
  { id:"emergency", emoji:"🛡️", title:"Emergency Fund First", tagline:"Your financial foundation", riskLevel:"None", readTime:"5 min", description:"Before any investment, you need 3-6 months of expenses saved in a high-yield savings account. This is step zero.", content:`**Why emergency fund first?**\nIf you invest without an emergency fund, a car repair or medical bill forces you to sell investments at the wrong time.\n\n**The rule:** Save 3-6 months of living expenses in a liquid, accessible account.\n\n**Best accounts for emergency fund:**\n- High-Yield Savings Account (HYSA) at Marcus, Ally, or SoFi\n- Current rates: 4.5% - 5% APY (much better than big bank savings)\n- No market risk, FDIC insured up to $250,000\n\n**How to calculate your number:**\nMonthly expenses × 4 = minimum emergency fund\nExample: $3,000/month × 4 = $12,000 target\n\n**Once funded:** You're ready to invest surplus money toward your goals.` },
];

export const blogPosts = [
  { id:"pay-yourself-first", emoji:"💡", category:"Mindset", readTime:"4 min", title:"Pay Yourself First: The One Habit That Changes Everything", summary:"Most people spend first and save whatever's left. This one flip changes your financial future forever.", content:`Most people follow: Earn → Spend → Save whatever's left. The problem? There's usually nothing left.\n\n**The Flip**\nSuccessful savers follow: Earn → Save first → Spend what remains. This is called "paying yourself first."\n\n**How to automate it:**\n1. On payday, auto-transfer 10-20% to a separate savings account\n2. Treat this like rent — non-negotiable\n3. Spend the rest freely — no guilt\n\n**The math:** $200/month at 8% annual return over 20 years = $118,000. Same $200 but starting 5 years later = only $76,000. The 5-year delay cost you $42,000.` },
  { id:"beginner-mistakes", emoji:"🚫", category:"Beginner Guide", readTime:"5 min", title:"7 Mistakes Every Beginner Makes (And How to Avoid Them)", summary:"Everyone makes money mistakes. These 7 are the most common — and easiest to avoid.", content:`**Mistake 1:** Waiting until you "know enough." Start small and learn as you go.\n\n**Mistake 2:** No emergency fund before investing. A crisis forces panic selling.\n\n**Mistake 3:** Panic-selling in downturns. Markets recover. Panic selling locks in losses.\n\n**Mistake 4:** Chasing hot stock tips. No such thing as guaranteed returns.\n\n**Mistake 5:** Ignoring fees. A 1% annual fee cuts your 30-year wealth by 25%.\n\n**Mistake 6:** Not diversifying. Never put all money in one stock.\n\n**Mistake 7:** Not starting early. Time in the market beats timing the market every time.` },
  { id:"goal-based-saving", emoji:"🎯", category:"Strategy", readTime:"6 min", title:"How to Save for a Big Purchase Without Going Broke", summary:"Whether it's a car, home, or vacation — this framework tells you exactly how much to invest and where.", content:`**The goal-based saving framework:**\n1. Name your goal (car, down payment, vacation)\n2. Set a specific dollar target\n3. Set a timeline\n4. Calculate monthly savings needed\n5. Pick the right investment vehicle based on timeline\n\n**Matching timeline to investment:**\n- Under 1 year: High-yield savings account (no risk)\n- 1-3 years: Mix of HYSA + short-term bonds\n- 3-5 years: 60% bonds, 40% broad ETFs\n- 5+ years: Broad index ETFs (S&P 500, VTI)\n\n**The car example:**\n$25,000 car in 3 years. Need $700/month saved. Put in 60% BND + 40% HYSA. At average returns, you'll have $26,200 — enough for the car and taxes.` },
];

export const goalOptions = [
  { id:"car", label:"Car or Vehicle", emoji:"🚗", avgCost:25000, dealers:true },
  { id:"home", label:"Home Purchase", emoji:"🏠", avgCost:300000, dealers:true },
  { id:"vacation", label:"Vacation or Travel", emoji:"✈️", avgCost:5000, dealers:false },
  { id:"education", label:"Education Fees", emoji:"🎓", avgCost:15000, dealers:false },
  { id:"emergency", label:"Emergency Fund", emoji:"🛡️", avgCost:12000, dealers:false },
  { id:"retirement", label:"Retirement", emoji:"🌅", avgCost:500000, dealers:false },
  { id:"business", label:"Start a Business", emoji:"💼", avgCost:20000, dealers:false },
  { id:"other", label:"Something Else", emoji:"⭐", avgCost:10000, dealers:false },
];

export const investmentOptions = [
  { id:"hysa", name:"High-Yield Savings", ticker:"HYSA", emoji:"🏦", risk:"None", avgReturn:4.8, timeframe:"Any", bestFor:"Under 1 year goals", description:"FDIC-insured savings account paying 4.5-5% APY. Zero risk. Perfect for short-term goals.", platform:"Marcus by Goldman Sachs, Ally Bank, SoFi", referralNote:"Open an account with our partner links and earn a signup bonus" },
  { id:"bonds", name:"US Treasury Bonds", ticker:"BND", emoji:"🇺🇸", risk:"Very Low", avgReturn:4.5, timeframe:"1-3 years", bestFor:"Conservative savers", description:"Backed by the US government. Buy directly at TreasuryDirect.gov or through bond ETFs like BND.", platform:"TreasuryDirect.gov, Fidelity, Schwab", referralNote:"We earn a small referral fee when you open a brokerage account" },
  { id:"etf", name:"S&P 500 Index ETF", ticker:"VOO", emoji:"📈", risk:"Medium", avgReturn:10.0, timeframe:"3-5+ years", bestFor:"Long-term wealth building", description:"Own the 500 largest US companies in one fund. Lowest fees, best long-term track record.", platform:"Fidelity, Schwab (both $0 commission)", referralNote:"Open a Fidelity account through our link — they offer cash bonuses for new accounts" },
  { id:"realestate", name:"Real Estate ETF", ticker:"VNQ", emoji:"🏘️", risk:"Medium", avgReturn:9.0, timeframe:"3-5+ years", bestFor:"Real estate exposure without a mortgage", description:"Invest in hundreds of real estate companies. Pays regular dividends from rental income.", platform:"Vanguard, Fidelity, Schwab", referralNote:"No minimum investment required through any major brokerage" },
];

export function calculateSavingsPlan(targetAmount: number, monthlyContribution: number, annualReturn: number) {
  const monthlyRate = annualReturn / 100 / 12;
  let balance = 0;
  let months = 0;
  while (balance < targetAmount && months < 600) {
    balance = balance * (1 + monthlyRate) + monthlyContribution;
    months++;
  }
  return { months, years: Math.floor(months / 12), remainingMonths: months % 12, finalBalance: balance };
}
